import 'package:flutter/material.dart';
import 'package:login_register_screen_firebase/utulits/constant/colorconstant.dart';
import 'package:login_register_screen_firebase/utulits/constant/image_constant.dart';
import 'package:login_register_screen_firebase/widgets/DownloadPDFContainer.dart';
import 'package:login_register_screen_firebase/widgets/EarningAmount_container.dart';
import 'package:login_register_screen_firebase/widgets/EmployeeSummary.dart';
import 'package:login_register_screen_firebase/widgets/TotalNetPayableContainer.dart';
import 'package:login_register_screen_firebase/widgets/employeeAcountDetails.dart';
import 'package:login_register_screen_firebase/widgets/payslipHistoryContainer.dart';
import 'package:login_register_screen_firebase/widgets/ziyalog.dart';

class PayslipScrenn extends StatefulWidget {
  const PayslipScrenn({super.key});

  @override
  State<PayslipScrenn> createState() => _PayslipScrennState();
}

class _PayslipScrennState extends State<PayslipScrenn> {
 String selectedMonth = 'June 2025';
  String selectedMoney = '₹45,000';

  void updateSelectedMonth(String newMonth) {
    setState(() {
      selectedMonth = newMonth;
    });
  }

  void updateSelectedMoney(String newMoney) {
    setState(() {
      selectedMoney = newMoney;
    });
  }
  @override
Widget build(BuildContext context) {
  return WillPopScope(
    onWillPop: () async {
      Navigator.pop(context);
      return false;
    },
    child: Scaffold(
      appBar: AppBar(
        elevation: 0,
        leading: Padding(
          padding: const EdgeInsets.all(5),
          child: CircleAvatar(
            radius: 22,
            backgroundImage: NetworkImage(ImageConst.appbarimage),
          ),
        ),
        title: Material(
          elevation: 2,
          shape: BeveledRectangleBorder(borderRadius: BorderRadius.circular(5)),
          child: Container(
            height: 45,
            padding: const EdgeInsets.symmetric(horizontal: 12),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(5),
              color: Colors.white,
            ),
            alignment: Alignment.centerLeft,
            child: Text(
              'Search',
              style: TextStyle(
                fontSize: 14,
                color: Colorconstant.lightgrey,
              ),
            ),
          ),
        ),
        actions: [
          CircleAvatar(
            radius: 15,
            backgroundColor: Colors.blue,
            child: Icon(Icons.notifications, color: Colors.white),
          ),
          SizedBox(width: 10),
          CircleAvatar(
            radius: 15,
            backgroundImage: NetworkImage(ImageConst.profileimage),
          ),
          SizedBox(width: 10),
        ],
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start, 
              children: [
                ziyalog(selectedMonth: selectedMonth),
                const Divider(),
                employeeSummary(
                  selectedMonth: selectedMonth,
                  selectedMoney: selectedMoney,
                ),
                const Divider(),
                employeeAcountDetails(),
                const SizedBox(height: 10),
                EarningAmount_container(selectedMoney: selectedMoney),
                const SizedBox(height: 5),
                TotalNetPayableContainer(selectedMoney: selectedMoney),
                const SizedBox(height: 10),

              
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      "Amount in Words: ",
                      style: TextStyle(fontSize: 12),
                    ),
                    Expanded(
                      child: Text(
                        "Indian Rupee Forty-Five thousand Only",
                        style: TextStyle(fontSize: 12),
                        overflow: TextOverflow.visible,
                      ),
                    ),
                  ],
                ),

                const SizedBox(height: 20),
                const Divider(),
                const Center(
                  child: Text(
                    "This document has been automatically generated by Ziya Academy",
                    style: TextStyle(fontSize: 12, color: Colorconstant.darkgrey),
                    textAlign: TextAlign.center,
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(10),
                  child: DownloadPDFContainer(
                    selectedMonth: selectedMonth,
                    selectedMoney: selectedMoney,
                  ),
                ),
                const SizedBox(height: 10),
                const Text(
                  "Monthly payslip History",
                  style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 10),
                payslipHistoryContainer(
                  onMonthSelected: updateSelectedMonth,
                  onMoney: updateSelectedMoney,
                ),
              ],
            ),
          ),
        ),
      ),
    ),
  );
}

}

