import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

Future<void> generatePrintContainerPDF({
  required String selectedMonth,
  required String selectedMoney,
}) async {
  final pdf = pw.Document();

  pdf.addPage(
    pw.Page(
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text("Ziya Academy", style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 5),
          pw.Text("Key-To-Success", style: pw.TextStyle(fontSize: 14)),
          pw.SizedBox(height: 15),

          pw.Text("Payslip for the Month: $selectedMonth", style: pw.TextStyle(fontSize: 16)),
          pw.SizedBox(height: 20),

          pw.Text("EMPLOYEE SUMMARY", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),

          pw.Text("Employee Name: John Doe"),
          pw.Text("Designation: Software Engineer"),
          pw.Text("Employee ID: ZYA1234"),
          pw.Text("Date of Joining: 01-Jan-2023"),
          pw.Text("Pay Period: $selectedMonth"),
          pw.Text("Pay Date: 01-${selectedMonth.split(" ")[0]}-2025"),

          pw.Divider(),
          pw.SizedBox(height: 10),

          pw.Text("ACCOUNT DETAILS", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 5),
          pw.Text("Bank Name: ABC Bank"),
          pw.Text("Account Number: ****1234"),
          pw.Text("IFSC Code: ABCD0001234"),

          pw.SizedBox(height: 15),

          
          pw.Text("EARNINGS & DEDUCTIONS", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),

          pw.Table.fromTextArray(
            headers: [
              'EARNINGS',
              'AMOUNT',
              'YTD',
              'DEDUCTIONS',
              'AMOUNT',
              'YTD',
            ],
            data: [
              ['Basic', '₹25,000', '₹3,00,000', 'PF Deduction', '₹2,500', '₹30,000'],
              ['HRA', '₹10,000', '₹1,20,000', 'Tax Deduction', '₹7,500', '₹90,000'],
              ['Travel Allowance', '₹3,000', '₹36,000', '', '', ''],
              ['Meal/Other Allowance', '₹2,000', '₹24,000', '', '', ''],
            ],
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            cellAlignment: pw.Alignment.centerLeft,
            cellStyle: pw.TextStyle(fontSize: 10),
            columnWidths: {
              0: pw.FixedColumnWidth(80),
              1: pw.FixedColumnWidth(60),
              2: pw.FixedColumnWidth(60),
              3: pw.FixedColumnWidth(100),
              4: pw.FixedColumnWidth(60),
              5: pw.FixedColumnWidth(60),
            },
          ),

          pw.SizedBox(height: 15),

          pw.Container(
            color: PdfColors.blue100,
            padding: pw.EdgeInsets.all(8),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text("Gross Earnings: ₹55,000", style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                pw.Text("Total Deductions: ₹10,000", style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                pw.Text("Net Payable: $selectedMoney", style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              ],
            ),
          ),

          pw.SizedBox(height: 20),
          pw.Text("Amount in Words: Indian Rupee ${selectedMoney.replaceAll("₹", "")} Only"),
          pw.SizedBox(height: 30),
          pw.Text(
            "This document has been automatically generated by Ziya Academy",
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey),
          ),
        ],
      ),
    ),
  );

  await Printing.layoutPdf(onLayout: (format) async => pdf.save());
}
